==== Run Ansible Homework Assignment and grade

Run Ansible Homework Assignment and grade
update GUIDs to the one provisioned:

66ac - GUID PROD_ANS_TOWER_HOMEWORK_LAB

2237 - GUID Ansible_Advance_OSP_ENV_v5.6-i-8ccc

32c6 - GUID PROD_THREE_TIER_APP (update GUID after 3TierApp environment will be provisioned) #

# Ansible tower node:
https://tower1.66ac.example.opentlc.com
admin
r3dh4t1!

#bastion host to connect using ssh key (.ppk file in putty)
mitko.mihaylov-atos.net@bastion.66ac.example.opentlc.com

#copy private key to access workstation and configure necessary permissions to access that key
sudo -i
vim /root/.ssh/mykey.pem
chmod 400 /root/.ssh/mykey.pem
chown root:root /root/.ssh/mykey.pem

# remove hashed lines from openstack public certificate
sed -i '/^#/ d'  /root/.ssh/openstack.pem
# sed -i '/^#/ d'  /root/.ssh/openstack.pub

#verify that it is possible to connect to OSP workstation
ssh -i /root/.ssh/mykey.pem mitko.mihaylov-atos.net@workstation-2237.rhpds.opentlc.com

#clone github repo
git clone https://github.com/mitko-mihaylov/ansible_advance_homework.git

cd ansible_advance_homework
OSP_GUID=2237
ansible-playbook site-setup-workstation.yml -e OSP_GUID=${OSP_GUID} --private-key=/root/.ssh/mykey.pem -u mitko.mihaylov-atos.net

#verify that it is possible to connect to OSP workstation with cloud-user
ssh -i /root/.ssh/openstack.pem cloud-user@workstation-2237.rhpds.opentlc.com

TOWER_GUID=66ac
OSP_GUID=2237
OPENTLC_LOGIN=mitko.mihaylov-atos.net
OPENTLC_PASSWORD=Ma313028*
GITHUB_REPO=https://github.com/mitko-mihaylov/ansible_advance_homework.git
JQ_REPO_BASE=http://www.opentlc.com/download/ansible_bootcamp
REGION=eu-central-1
RH_MAIL_ID=mitko.mihaylov@atos.net

ansible-playbook site-install-isolated-node.yml -e TOWER_GUID=${TOWER_GUID} -e OSP_GUID=${OSP_GUID} -e opentlc_login=${OPENTLC_LOGIN} -e path_to_opentlc_key=/root/.ssh/mykey.pem -e param_repo_base=${JQ_REPO_BASE} -e opentlc_password=${OPENTLC_PASSWORD} -e REGION_NAME=${REGION} -e EMAIL=${RH_MAIL_ID} -e github_repo=${GITHUB_REPO}

ansible-playbook site-config-tower.yml -e tower_GUID=${TOWER_GUID} -e osp_GUID=${OSP_GUID} -e opentlc_login=${OPENTLC_LOGIN} -e path_to_opentlc_key=/root/.ssh/mykey.pem -e param_repo_base=${JQ_REPO_BASE} -e opentlc_password=${OPENTLC_PASSWORD} -e REGION_NAME=${REGION} -e EMAIL=${RH_MAIL_ID} -e github_repo=${GITHUB_REPO}

# grading
OSP_GUID=2237
ANSIBLE_ADVANCE_GUID=32c6 
ansible-playbook grading-script.yml -e OSP_GUID=${OSP_GUID} -e ANSIBLE_ADVANCE_GUID=${ANSIBLE_ADVANCE_GUID}
----

.List of Playbooks
[%header,cols=2*]
|===
| Files or dir | Purpose
| app-tier | Install application server role
| db-tier  | Install postgressql server for database role
| lb-tier  | Install HA proxy role
| base-config | Setup yum repo and base packages role
| setup-workstation | Setup workstation, create network, ssh keypair, security group etc. role 
| osp-servers | Provision OSP Instances role
| osp-instance-delete | Delete OSP Instances role
| osp-facts | Genrate in-memory inventory for OSP instances role
| roles/config-tower/vars/main.yml | Very important file to review. All the variable values are set there. Please do not make any changes in the file
| config-tower | Role to configure ansible tower job templates and workflow
| aws_creds.yml | Fetch GUIDkey.pem from bastion of Three tier application env and create machine credential to connect to AWS instances
| aws_provision.yml | Use `order_svc.sh` script to provision env
| aws_status_check.yml | Check aws instances are up or not
| site-3tier-app.yml | Playbook to deploy three tier app
| site-install-isolated-node.yml | Playbook to install isolated node
| site-config-tower.yml | Playbook to call role `config-tower`
| site-osp-delete.yml | Playbook to call role
| site-osp-instances.yml | Playbook to call role
| site-setup-workstation.yml | Playbook to call role
| site-smoke-osp.yml | Playbook to test three tier app on OSP
| site-smoketest-aws.yml | Playbook to test three tier app on AWS
| grading-script.yml | Self grading script
| roles/config-tower/tasks/ec2_dynamic.yml | For creating Dynamic inventory in Ansible tower. Use `AWS Access Key` for credential
| roles/config-tower/tasks/job_template.yml | For creating job templates
| roles/config-tower/tasks/pre-config-tower.yml | Any pre config tasks needed
| roles/config-tower/tasks/workflow_template.yml | genrate workflow from `workflow.yml` file
| roles/config-tower/tasks/post-config-tower.yml | any post config jobs
|===
